apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varsler-frontend
  namespace: min-side
  labels:
    team: min-side
spec:
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /minside/varsler-ny/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/varsler-ny/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: tms-varsel-api
  ingresses:
    - "https://www.intern.dev.nav.no/minside/varsler-ny"
    - "https://www.ansatt.dev.nav.no/minside/varsler-ny"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: TMS_VARSLER_API_URL
      value: "http://tms-varsel-api/alle"
    - name: TMS_APP_BASE_URL
      value: "https://www.ansatt.dev.nav.no/minside/varsler-ny"
    - name: TMS_MIN_SIDE_URL
      value: "https://www.ansatt.dev.nav.no/minside"